### ISSUE TITLE
New record button opens Main form instead of Quick create form

### ISSUE THREAD

**Issue by denikqwerty** [BeverCRM/PCF-DragAndDropGrid#28]
Once we enabled your PCF control for our grid. New record which is initiated by clicking + button on the top of the grid, now opens Main form, but previously it was opening Quick Create form. Once we disable PCF control, Quick Create form used. Can you please fix this issue, so the behavior of the new record creation should be the same as OOB

**Comment by Hovhannes-Dilanyan** [comment]
Hi @denikqwerty 

Thank you for reporting the bug! We appreciate your contribution to improving our project.
The fix has been implemented in [Release v1.0.1](https://github.com/BeverCRM/PCF-DragAndDropGrid/releases/tag/v1.0.1)
You can download it here [Bever Marketplace](https://marketplace.bevercrm.com/pcf-controls/2)

If you have any further questions or encounter any other issues, please feel free to reach out.

Best Regards,
Hovhannes

**Comment by denikqwerty** [comment]
Thank you for quick approval and release :)
